Show rasteplass on map
bekk/ruteplanlegger-frontend pull request #11
Opened 2023-09-06 13:41 UTC by purusott

Viser rasteplasser fra SVV på kartet som "Markers" (punkter). Henter rasteplasser fra backend og bruker React Leaflet sine komponenter til å vise frem data. 

Det ligger kode som også tar hensyn til om datapunktet er Linestring eller Polygon, så det kan også vises om nødvendig.

Hvert punkt har en popup som viser litt mer info om selve rasteplassen 

![Screenshot 2023-09-06 at 15 37 04](https://github.com/bekk/ruteplanlegger-frontend/assets/74315929/840a1d18-245f-4602-8556-ddaf2d81e768)

2023-09-07 11:02 UTC, emilielr requested changes
Mye bra :D Bare en del småkommentarer på hvorfor egt

2023-09-07 11:02 UTC, emilielr commented on src/vite-env.d.ts
> +  geometri: any;
bruker vi denne?

2023-09-07 11:02 UTC, emilielr commented on src/vite-env.d.ts
> +  coordinates?: any;
kan denne være noe annet enn any? vi får double fra backend

2023-09-07 11:02 UTC, emilielr commented on src/vite-env.d.ts
> +export type Attraksjon = Rasteplass | Rasteplass;
Hvorfor er det to Rasteplass?

2023-09-07 11:02 UTC, RagnhildK requested changes

2023-09-07 11:05 UTC, RagnhildK commented on src/vite-env.d.ts
> +  coordinates?: any;
Må vi har `coordinates?` her, eller kan vi bytte til `coordinates`? Vi har vel koordinater på alt vi sender til frontend 🤔

2023-09-07 11:19 UTC, purusott commented on src/views/MapView.tsx
>        center={positionOslo}
ta center litt lenger opp enn Oslo

2023-09-07 11:28 UTC, emilielr commented
En kommentar til: Endre at vi bruker Attraksjoner til Aktiviteter (f. eks ENUM-en)

2023-09-07 12:50 UTC, purusott commented on src/vite-env.d.ts
> +export type Attraksjon = Rasteplass | Rasteplass;
my bad 😆

2023-09-07 12:55 UTC, purusott commented on tsconfig.json
> +    "noUnusedParameters": false,
TS klager når vi builder med CI/CD, så skrudde det av i tsconfig. Ellers lot den ikke nam build kjøre ferdig 😟

2023-09-07 13:08 UTC, purusott commented on src/vite-env.d.ts
> +  coordinates?: any;
gjort om så det ligner på model i backend. 

Rasteplass har Geometri av typen geometri
Geometri har type (String) og coordinates (latlong)
coordinates har lat og long

2023-09-07 13:09 UTC, purusott commented on src/vite-env.d.ts
> +  coordinates?: any;
byttet så det ser ut som de samme typene vi har i backend

2023-09-08 06:31 UTC, purusott commented on src/utils/MapDesignOptions.ts
> +export const purpleOptions = { color: "purple" };
Et eksempel tatt fra [React Leaflet dokumentasjonen](https://react-leaflet.js.org/docs/example-vector-layers/) på hvordan man kan velge farger på objekter (Polygon, Linestring, ..) man tegner på kartet

2023-09-08 06:32 UTC, purusott commented on src/views/MapView.tsx
> +                    {": "} {aktivitet.vegkategori}
Bruker den funksjonen nå til å vise vegnavn :)

2023-09-08 06:45 UTC, emilielr commented on src/vite-env.d.ts
> +export type Aktivitet = RasteplassType | KunstType;
Endre Aktivitet til AktivitetType

2023-09-08 06:47 UTC, emilielr commented on src/App.tsx
> +export enum Aktiviteter {
Endre til AktiviteterEnum

2023-09-08 08:39 UTC, RagnhildK commented on src/views/KunstView.tsx
> +      "https://ruteplanlegger-for-turister.onrender.com/kunst"
Kan vi endre denne til å bruke urlen definert i API_URLs.ts?

2023-09-08 08:39 UTC, RagnhildK commented on src/views/RasteplassView.tsx
> +      "https://ruteplanlegger-for-turister.onrender.com/rasteplasser"
Samme som kommentaren i KunstView.tsx

2023-09-08 08:43 UTC, purusott commented on src/views/KunstView.tsx
> +      "https://ruteplanlegger-for-turister.onrender.com/kunst"
gjort det nå :)

2023-09-08 08:43 UTC, purusott commented on src/views/RasteplassView.tsx
> +      "https://ruteplanlegger-for-turister.onrender.com/rasteplasser"
done :)

2023-09-08 08:55 UTC, emilielr approved these changes

2023-09-08 08:55 UTC, merged