Design checkboxes og legge til tittel
bekk/ruteplanlegger-frontend pull request #14
Opened 2023-09-11 12:19 UTC by emilielr

Har fjernet en god del ubrukt CSS, og lagt til et theme. Ved å legge til et `theme` kan man overstyre default chakra-komponenter + gjøre at noen styling er global. 

Også flyttet checkboxen ut i en egen komponent_: `CheckboxGroup`. 

![image](https://github.com/bekk/ruteplanlegger-frontend/assets/43408175/6d1a0f11-a300-4e62-8af8-76f4bc157df3)

2023-09-11 12:35 UTC, purusott commented on src/main.tsx
> +    <ChakraProvider theme={theme}>
Blir denne brukt "automatisk" der det trengs globalt eller må man spesifisere det selv i komponenter (med f.eks. theme.fonts elns) ?

2023-09-11 12:36 UTC, purusott approved these changes
Bra å trekke ut checkbox til sin egen komponent! LGTM visuelt 🥇

2023-09-12 08:18 UTC, emilielr commented on src/main.tsx
> +    <ChakraProvider theme={theme}>
Den blir det automatisk! Fonts er hvertfall automatisk, også når man skriver <h2>-tagen, så får man stylingen som er definert i theme for h2.

2023-09-12 08:22 UTC, purusott commented on src/main.tsx
> +    <ChakraProvider theme={theme}>
Nice 🤠

2023-09-12 08:26 UTC, RagnhildK requested changes
Ser bra ut! Endre det vi snakket om med value istedenfor label på chackboxene og så er vi goood

2023-09-12 08:26 UTC, RagnhildK commented on src/components/CheckboxGroup.tsx
> +      value: "Hent Rasteplass",
Endre value til AktiviteterEnum.Rasetplass og sende den videre i linke 46 i stedenfor checkbox.label

2023-09-12 08:26 UTC, RagnhildK commented on src/components/CheckboxGroup.tsx
> +      value: "Hent Kunst",
Samme som over

2023-09-12 08:45 UTC, RagnhildK approved these changes
Looks good 🎉

2023-09-12 08:45 UTC, merged