Vise Fotruter i listeformat
bekk/ruteplanlegger-frontend pull request #15
Opened 2023-09-11 13:35 UTC by purusott

Resultat: Ligger en checkbox for å vise fotruter, og når man klikker på den vil de vises i listeformat
![Screenshot 2023-09-11 at 15 24 41](https://github.com/bekk/ruteplanlegger-frontend/assets/74315929/7cdc848b-3912-41af-bc4f-ca45ad33653f)

Logikk:

- Oppdatere checkboxState til å vise fotruter (legge til en tilsvarende ny linje)
- Oppdatere enums til å ha med fotruter og API_URL til å peke på lokal backend
- Lage Fotruteview (her hentes fotruter fra backend/lokalt) og FotruteCard (viser frem info), som er lik RasteplassView + RasteplassCard

NB: må ha nyeste versjon av [backend](https://github.com/bekk/ruteplanlegger-backend/tree/fotruter-research) at denne skal kunne funke lokalt. Den ligger i en branch som ikke er merget inn

2023-09-12 08:12 UTC, RagnhildK requested changes
Ser bra ut, men syns vi skal lage en PR på backend og få den deployet slik at vi kan bruke riktig link før vi merger denne inn.

2023-09-12 08:28 UTC, emilielr requested changes
Småpirk, eller ser det bra ut 🎖️

2023-09-12 08:41 UTC, emilielr commented on src/components/CheckboxGroup.tsx
> +      checked: checkboxState.Fotrute,
Endre denne til: 
```
{
      label: "Fotruter,
      value: AktiviteterEnum.Fotrute,
      checked: checkboxState.Fotrute,
    }
```

2023-09-12 08:43 UTC, purusott commented on src/views/FotruteView.tsx
> +    console.log(data);
done

2023-09-12 08:44 UTC, purusott commented on src/views/FotruteView.tsx
> +          return <FotruteCard fotrute={fotrute} />;
nice! var først fotrute.navn i key, men fjernet det siden flere hadde samme navn + glemte at man kan bruke index 😅

2023-09-12 08:51 UTC, purusott commented on src/components/CheckboxGroup.tsx
> +      checked: checkboxState.Fotrute,
done 👍

2023-09-12 11:17 UTC, emilielr approved these changes
LGTM 👯

2023-09-13 08:01 UTC, RagnhildK approved these changes
Wiii

2023-09-13 08:01 UTC, merged