Anbefalte aktiviteter
bekk/ruteplanlegger-frontend pull request #28
Opened 2023-09-25 13:13 UTC by RagnhildK

**Min tolkning av "use cases":** 
Dersom man huker av for rasteplasser vil man få opp anbefalte rasteplasser i en egen liste øverst. _De anbefalte rasteplassene vil også vises i den "vanlige" rasteplass-listen lenger ned på siden._ Dersom man huker av for K/U hvor det ikke finnes noen anbefalte element vil man ikke se den anbefalte listen i det hele tatt. Dersom man derimot har huket av for både K/U og Fotruter vil man få opp en liste med Anbefalte stopp som inkluderer den ene fotruten som er anbefalt. _Vi har totalt 8 anbefalte rasteplasser og 1 anbefalt fotrute._

**Litt teknisk forklaring:**

- Har lagt inn en egen komponent som rendrer listen med anbefalte stopp øverst på siden (AnbefalteAktiviteter.tsx). 
- Flyttet apikallene ut fra RasteplassList, KunstList og FotruteList og til ListView slik at AnbefalteAktiviteter kunne bruke samme data uten å gjøre nye kall. 
- Har også trukket deler av kode i RasteplassList, KunstList og FotruteList ut til RasteplassCard, KunstCard og FotruteCard for å kunne gjenbruke den i AnbefalteAktiviteter. 

OBS: Det er mye greier som er gjort her, så det er helt sikkert en del å pirke på også. Fyr løs!

**Småting som er gjort på design:** 
Tittelen er nå i h1, ikke h2. 
Og det er lagt inn en del spacing mellom anbefalte stopp listen og det som kommer under
![image](https://github.com/bekk/ruteplanlegger-frontend/assets/41580514/917f90a9-e879-462e-86bd-cb34e24bde65)

2023-09-25 13:38 UTC, emilielr commented on src/components/AnbefalteAktiviteter.tsx
> +interface AktivitetTypeProps {
Kan vi kalle denne `AnbefalteAktiviteterProps` slik som vi gjør på alle andre interfaces?

2023-09-25 13:56 UTC, emilielr requested changes
Mye kommentarer, men omhandler mye av det samme. Jeg synes det er litt knotete med å ha en liste -> rasteplasscard-> generic card, men vi kan heller fikse at koden er smudere på et senere tidspunkt. Bra jobba!

2023-09-25 13:56 UTC, emilielr commented on src/components/AnbefalteAktiviteter.tsx
> +    <>
Trenger vi å ha med denne <>? Eventuelt gjøre noe annet med <> som `<section> `eller `<main> `(vet ikke helt hva som er mest riktig, men tror section kan gjøre seg). Hilsen a11y/WCAG-politiet

2023-09-25 13:56 UTC, emilielr commented on src/components/AnbefalteAktiviteter.tsx
> +          {getAnbefalteAktiviteter(alleAktiviteter).map(
Vi kaller på getAnbefalteAktiviteter to ganger her (linje 27 og 24). Kan vi sette dette ut i en variabel (eller kjøre på en useEffect() eller en hook?) slik at den kun trenger å gjøres èn gang?

2023-09-25 13:56 UTC, emilielr commented on src/vite-env.d.ts
> +  anbefalt: boolean;
Legge til id med det samme?

2023-09-25 13:56 UTC, emilielr commented on src/components/FotruteCard.tsx
> +      key={index}
I stedet for å ta inn index her kan vi nå bruke ID som kommer med fotruter. Da kan vi fjerne index fra FotruteProps, og heller skrive `key={fotrute.id}`. Slik vi har gjort i rasteplass og kunst.

2023-09-25 13:56 UTC, emilielr commented on src/components/FotruteCard.tsx
> +interface FotruteProps {
Gjerne kall denne FotruteCardProps. Ser nå at det er to interaces som heter det samme som ligger i henholdsvis FotruteList og her. Jeg synes det er greit at interfacen heter komponentnavnet + Props. Det er nok litt smak og behag og, men da vet man at denne tilhører FotruteCard.

2023-09-25 13:56 UTC, emilielr commented on src/components/FotruteList.tsx
> +interface FotruteProps {
Her, kall den FotruteListProps

2023-09-25 13:56 UTC, emilielr commented on src/components/KunstCard.tsx
> +interface KunstProps {
KunstCardProps

2023-09-25 13:56 UTC, emilielr commented on src/components/KunstList.tsx
> +interface KunstProps {
KunstListProps

2023-09-25 13:56 UTC, emilielr commented on src/components/KunstList.tsx
> +        return <KunstCard kunst={kunst} />;
ser vi sender med index her på rasteplass feks, trengs det å gjøres her og? Får vi feilmelding i consolen om unique child components?

2023-09-25 13:56 UTC, emilielr commented on src/components/RasteplassList.tsx
> +interface RasteplassProps {
RasteplassListProps

2023-09-25 13:56 UTC, emilielr commented on src/components/RasteplassList.tsx
> +        return <RasteplassCard rasteplass={rasteplass} />;
index her og på hvert kort?

2023-09-25 14:35 UTC, RagnhildK commented on src/components/AnbefalteAktiviteter.tsx
> +    <>
Aldri brukt noen av de før, men leste raskt på det og section tror jeg blir best, så inn section nå

2023-09-25 14:48 UTC, RagnhildK commented on src/components/KunstList.tsx
> +        return <KunstCard kunst={kunst} />;
La det inn på RasteplassList, KunstList og FotruteList nå, og i AnbefalteAktiviteter 
Får fortsatt en feilmelding i terminalen, men får se på den i morgen siden jeg ikke skjønner den nå :))

2023-09-26 06:18 UTC, purusott commented
Jeg er usikker på om vi skal ha use-casene så man får opp anbefalt fotrute, også den samme foruten igjen under (tilsvarende på rasteplass), altså dobbelt med "samme" kort 🤔 Hvis det blir for mye jobb å endre på det, kan vi nok ha det slik det er nå
 
![Screenshot 2023-09-26 at 08 14 33](https://github.com/bekk/ruteplanlegger-frontend/assets/74315929/0a087898-e525-4446-af58-b58c0d4e0c71)

2023-09-26 06:44 UTC, purusott commented on src/components/AnbefalteAktiviteter.tsx
> +          {getAnbefalteAktiviteter(alleAktiviteter).map(
+1 - use effect og usestate her er nok nice

2023-09-26 06:48 UTC, RagnhildK commented on src/components/AnbefalteAktiviteter.tsx
> +          {getAnbefalteAktiviteter(alleAktiviteter).map(
Satt den ut i en useEffekt og lagret resultatet i state nå

2023-09-26 07:02 UTC, purusott commented on src/views/ListView.tsx
> +    getAktivitetsData();
En tanke til senere kanskje: vi kjører potensielt flere kall når vi trykker på en checkbox - uavhengig av om man har dataen fra før eller ikke

2023-09-26 07:56 UTC, emilielr approved these changes

2023-09-26 07:58 UTC, merged