Rasteplasser med bilder
bekk/ruteplanlegger-frontend pull request #65
Opened 2023-10-16 11:30 UTC by purusott

**Styling**: overskriver leaflet klassene i  Popup.css for å ligne på skissene. Fant ikke skisser på hvordan det skal se ut om man ikke har bilde, så gikk ut i fra det Maria nevnte om å si til bruker at "det ikke er bilde her" for nå. Kan lett endre på det 👍 

**Teknisk**: 

- Lagde en ny fil `API_Image` som har koden for å hente vegbilder fra SVV. Man tar inn lat og long til rasteplassen, så lages bounding boxen rundt dette som sendes inn.  
- Lagde en eventlistener i `RasteplassMarker` der `getImage` kalles på når man trykker på en spesifikk popup

<img width="263" alt="Screenshot 2023-10-16 at 12 46 27" src="https://github.com/bekk/ruteplanlegger-frontend/assets/74315929/d2d0bcf8-20a5-4225-8730-d1de6acae2fe">
<img width="337" alt="Screenshot 2023-10-16 at 12 45 56" src="https://github.com/bekk/ruteplanlegger-frontend/assets/74315929/6a64ec13-23bd-465e-a1d7-8e8e0ec4a85c">

2023-10-16 11:53 UTC, RagnhildK commented
Skulle vi flyttet det close ikonet ned under bildet? Ref de bildene vi så på tidligere i dag hvor man ikke klarte å se ikonet pga mørk bakgrunn på bildet?

Og kanskje legge inn padding når det ikke er bilde?

2023-10-16 12:05 UTC, purusott commented
> Skulle vi flyttet det close ikonet ned under bildet? Ref de bildene vi så på tidligere i dag hvor man ikke klarte å se ikonet pga mørk bakgrunn på bildet?
> 
> Og kanskje legge inn padding når det ikke er bilde?

2023-10-16 13:33 UTC, RagnhildK requested changes

2023-10-16 13:33 UTC, RagnhildK commented on src/utils/API_URLs.ts
> +export const GET_VEGBILDE_URL = (bbox: string) =>
Flytte kallet til backend?

2023-10-17 07:22 UTC, purusott commented on src/components/Popup.css
> +  padding-left: 16px;
bra sett ! la ikke merke til det 😅

2023-10-17 07:23 UTC, purusott commented on src/components/rasteplass/RasteplassMarker.tsx
> +          maxHeight: "255px",
oki, gjort det nå :)

2023-10-23 09:50 UTC, emilielr commented on src/components/rasteplass/RasteplassMarker.tsx
> +            title="Rasteplass ikke funnet"
Endre title til "Bilde ikke funnet"?

2023-10-23 09:50 UTC, RagnhildK approved these changes

2023-10-23 09:53 UTC, emilielr approved these changes

2023-10-23 10:08 UTC, purusott commented on src/components/rasteplass/RasteplassMarker.tsx
> +            title="Rasteplass ikke funnet"
done

2023-10-23 10:10 UTC, merged